### ISSUE TITLE
`import pysal` in libpysal/io/iohandlers/dat.py

### ISSUE THREAD

**Issue by jGaboardi** [pysal/libpysal#144]
[Current TravisCI failures](https://travis-ci.org/pysal/libpysal/builds/505932023) appear to be due to an `import pysal` in [`libpysal/io/iohandlers/dat.py`](https://github.com/pysal/libpysal/blob/194fe03b5a39d92cd5d5742a1fffe27c5b10af7d/libpysal/io/iohandlers/dat.py#L86-L129).

```
======================================================================
FAIL: Doctest: libpysal.io.iohandlers.arcgis_dbf.ArcGISDbfIO.write
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysal/libpysal/miniconda/envs/test-env/lib/python3.6/doctest.py", line 2199, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for libpysal.io.iohandlers.arcgis_dbf.ArcGISDbfIO.write
  File "/home/travis/build/pysal/libpysal/libpysal/io/iohandlers/arcgis_dbf.py", line 143, in write
----------------------------------------------------------------------
File "/home/travis/build/pysal/libpysal/libpysal/io/iohandlers/arcgis_dbf.py", line 160, in libpysal.io.iohandlers.arcgis_dbf.ArcGISDbfIO.write
Failed example:
    import tempfile, pysal, os
Exception raised:
    Traceback (most recent call last):
      File "/home/travis/build/pysal/libpysal/miniconda/envs/test-env/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest libpysal.io.iohandlers.arcgis_dbf.ArcGISDbfIO.write[0]>", line 1, in <module>
        import tempfile, pysal, os
    ModuleNotFoundError: No module named 'pysal'
```

**Comment by jGaboardi** [comment]
And I have no idea why this is just failing now... @ljwolf

**Comment by jGaboardi** [comment]
Addressing in #142
