### ISSUE TITLE
GitHub Actions failures

### ISSUE THREAD

**Issue by jGaboardi** [pysal/libpysal#271]
Question in regarding current GitHub Actions failures:

https://github.community/t5/GitHub-Actions/Error-in-Python-testing-environment/m-p/51781

**Comment by sjsrey** [comment]
If we skip decorate the two voronoi tests, then the job [passes](https://github.com/sjsrey/libpysal/actions/runs/66008273)

**Comment by jGaboardi** [comment]
This a bizarre that it passed without issue yesterday and with weirdness today. But seems like we should have that skip test anyway since `geopandas` is not hard dependency? Shall we go ahead and do a PR including the `skip`?

**Comment by sjsrey** [comment]
For now I would say we keep testing for gp until we can figure out what is going on with the actions infrastructure. I was skipping them to see if there were other problems with GHA, so this at lease narrows it down to the missing geopandas import.

**Comment by jGaboardi** [comment]
After more reviewing and testing, this appears to be another `libgdal`/`fiona` issue causing hiccups in installing `geopandas` properly. Our `SKIPIF` check sets `geopandas` to not be available on `ImportError`, but does not check the specific message that is thrown. Maybe a `ModuleNotFoundError` would be more appropriate for the unavailability of `geopandas`, where `ImportError` is reserved for an actual problem with the install?

See full trace of test environment creation below.

```
(base) user:~ user$ conda create -n GEOTEST python=3.7
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/user/miniconda3/envs/GEOTEST

  added / updated specs:
    - python=3.7


The following NEW packages will be INSTALLED:

  ca-certificates    conda-forge/osx-64::ca-certificates-2019.11.28-hecc5488_0
  certifi            conda-forge/osx-64::certifi-2019.11.28-py37hc8dfbb8_1
  libcxx             conda-forge/osx-64::libcxx-9.0.1-1
  libffi             conda-forge/osx-64::libffi-3.2.1-h4a8c4bd_1007
  ncurses            conda-forge/osx-64::ncurses-6.1-h0a44026_1002
  openssl            conda-forge/osx-64::openssl-1.1.1e-h0b31af3_0
  pip                conda-forge/noarch::pip-20.0.2-py_2
  python             conda-forge/osx-64::python-3.7.6-h90870a6_5_cpython
  python_abi         conda-forge/osx-64::python_abi-3.7-1_cp37m
  readline           conda-forge/osx-64::readline-8.0-hcfe32e1_0
  setuptools         conda-forge/osx-64::setuptools-46.1.3-py37hc8dfbb8_0
  sqlite             conda-forge/osx-64::sqlite-3.30.1-h93121df_0
  tk                 conda-forge/osx-64::tk-8.6.10-hbbe82c9_0
  wheel              conda-forge/noarch::wheel-0.34.2-py_1
  xz                 conda-forge/osx-64::xz-5.2.4-h0b31af3_1002
  zlib               conda-forge/osx-64::zlib-1.2.11-h0b31af3_1006


Preparing transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate GEOTEST
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) user:~ user$ conda activate GEOTEST
INFO: deactivate-gfortran_osx-64.sh made the following environmental changes:
-DEBUG_FFLAGS=-march=nocona -mtune=core2 -ftree-vectorize -fPIC -fstack-protector -O2 -pipe -isystem /Users/user/miniconda3/include -march=nocona -mtune=core2 -ftree-vectorize -fPIC -fstack-protector -O2 -pipe -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments
-DEBUG_FORTRANFLAGS=-march=nocona -mtune=core2 -ftree-vectorize -fPIC -fstack-protector -O2 -pipe -isystem /Users/user/miniconda3/include -march=nocona -mtune=core2 -ftree-vectorize -fPIC -fstack-protector -O2 -pipe -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments
-F77=/Users/user/miniconda3/bin/x86_64-apple-darwin13.4.0-gfortran
-F90=/Users/user/miniconda3/bin/x86_64-apple-darwin13.4.0-gfortran
-F95=/Users/user/miniconda3/bin/x86_64-apple-darwin13.4.0-gfortran
-FC=/Users/user/miniconda3/bin/x86_64-apple-darwin13.4.0-gfortran
-FFLAGS=-march=nocona -mtune=core2 -ftree-vectorize -fPIC -fstack-protector -O2 -pipe -isystem /Users/user/miniconda3/include
-FORTRANFLAGS=-march=nocona -mtune=core2 -ftree-vectorize -fPIC -fstack-protector -O2 -pipe -isystem /Users/user/miniconda3/include
-GFORTRAN=/Users/user/miniconda3/bin/x86_64-apple-darwin13.4.0-gfortran
(GEOTEST) user:~ user$ conda install geopandas
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/user/miniconda3/envs/GEOTEST

  added / updated specs:
    - geopandas


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libnetcdf-4.7.4            |nompi_he461dc0_100         1.2 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         1.2 MB

The following NEW packages will be INSTALLED:

  attrs              conda-forge/noarch::attrs-19.3.0-py_0
  boost-cpp          conda-forge/osx-64::boost-cpp-1.72.0-hdf9ef73_0
  bzip2              conda-forge/osx-64::bzip2-1.0.8-h0b31af3_2
  cairo              conda-forge/osx-64::cairo-1.16.0-hec6a9b0_1003
  cfitsio            conda-forge/osx-64::cfitsio-3.470-h84d2f63_2
  click              conda-forge/noarch::click-7.1.1-pyh8c360ce_0
  click-plugins      conda-forge/noarch::click-plugins-1.1.1-py_0
  cligj              conda-forge/noarch::cligj-0.5.0-py_0
  curl               conda-forge/osx-64::curl-7.68.0-h8754def_0
  expat              conda-forge/osx-64::expat-2.2.9-h4a8c4bd_2
  fiona              conda-forge/osx-64::fiona-1.8.13-py37he71f6a4_0
  fontconfig         conda-forge/osx-64::fontconfig-2.13.1-h6b1039f_1001
  freetype           conda-forge/osx-64::freetype-2.10.1-h8da9a1a_0
  freexl             conda-forge/osx-64::freexl-1.0.5-h1de35cc_1002
  gdal               conda-forge/osx-64::gdal-3.0.4-py37h08e9697_2
  geopandas          conda-forge/noarch::geopandas-0.7.0-py_1
  geos               conda-forge/osx-64::geos-3.8.1-h4a8c4bd_0
  geotiff            conda-forge/osx-64::geotiff-1.5.1-h4bdff65_9
  gettext            conda-forge/osx-64::gettext-0.19.8.1-h46ab8bc_1002
  giflib             conda-forge/osx-64::giflib-5.2.1-h0b31af3_2
  glib               conda-forge/osx-64::glib-2.58.3-py37h7c187be_1003
  hdf4               conda-forge/osx-64::hdf4-4.2.13-h84186c3_1003
  hdf5               conda-forge/osx-64::hdf5-1.10.5-nompi_h3e39495_1104
  icu                conda-forge/osx-64::icu-64.2-h6de7cb9_1
  jpeg               conda-forge/osx-64::jpeg-9c-h1de35cc_1001
  json-c             conda-forge/osx-64::json-c-0.13.1-h1de35cc_1001
  kealib             conda-forge/osx-64::kealib-1.4.12-h2324030_0
  krb5               conda-forge/osx-64::krb5-1.16.4-h1752a42_0
  libblas            conda-forge/osx-64::libblas-3.8.0-16_openblas
  libcblas           conda-forge/osx-64::libcblas-3.8.0-16_openblas
  libcurl            conda-forge/osx-64::libcurl-7.68.0-h709d2b2_0
  libdap4            conda-forge/osx-64::libdap4-3.20.4-habf5908_0
  libedit            conda-forge/osx-64::libedit-3.1.20170329-hcfe32e1_1001
  libgdal            conda-forge/osx-64::libgdal-3.0.4-hbf8f8d6_2
  libgfortran        conda-forge/osx-64::libgfortran-4.0.0-2
  libiconv           conda-forge/osx-64::libiconv-1.15-h0b31af3_1006
  libkml             conda-forge/osx-64::libkml-1.3.0-h169b8f9_1011
  liblapack          conda-forge/osx-64::liblapack-3.8.0-16_openblas
  libnetcdf          conda-forge/osx-64::libnetcdf-4.7.4-nompi_he461dc0_100
  libopenblas        conda-forge/osx-64::libopenblas-0.3.9-h3d69b6c_0
  libpng             conda-forge/osx-64::libpng-1.6.37-hbbe82c9_1
  libpq              conda-forge/osx-64::libpq-12.2-h554dc5a_0
  libspatialindex    conda-forge/osx-64::libspatialindex-1.9.3-h4a8c4bd_3
  libspatialite      conda-forge/osx-64::libspatialite-4.3.0a-hbcd37d4_1037
  libssh2            conda-forge/osx-64::libssh2-1.8.2-hcdc9a53_2
  libtiff            conda-forge/osx-64::libtiff-4.1.0-ha78913b_3
  libwebp            conda-forge/osx-64::libwebp-1.0.2-hd3bf737_5
  libxml2            conda-forge/osx-64::libxml2-2.9.10-h53d96d6_0
  llvm-openmp        conda-forge/osx-64::llvm-openmp-9.0.1-h28b9765_2
  lz4-c              conda-forge/osx-64::lz4-c-1.8.3-h6de7cb9_1001
  munch              conda-forge/noarch::munch-2.5.0-py_0
  numpy              conda-forge/osx-64::numpy-1.18.1-py37h7687784_1
  openjpeg           conda-forge/osx-64::openjpeg-2.3.1-h254dc36_3
  pandas             conda-forge/osx-64::pandas-1.0.3-py37h94625e5_0
  pcre               conda-forge/osx-64::pcre-8.44-h4a8c4bd_0
  pixman             conda-forge/osx-64::pixman-0.38.0-h01d97ff_1003
  poppler            conda-forge/osx-64::poppler-0.67.0-h16886b5_8
  poppler-data       conda-forge/noarch::poppler-data-0.4.9-1
  postgresql         conda-forge/osx-64::postgresql-12.2-h16d8c28_0
  proj               conda-forge/osx-64::proj-6.3.1-h773a61f_1
  pyproj             conda-forge/osx-64::pyproj-2.6.0-py37hf6d6e9e_0
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  pytz               conda-forge/noarch::pytz-2019.3-py_0
  rtree              conda-forge/osx-64::rtree-0.9.4-py37h8526d28_1
  shapely            conda-forge/osx-64::shapely-1.7.0-py37hfcf0db4_2
  six                conda-forge/noarch::six-1.14.0-py_1
  tbb                conda-forge/osx-64::tbb-2018.0.5-h2d50403_0
  tiledb             conda-forge/osx-64::tiledb-1.7.0-hd5e958f_2
  tzcode             conda-forge/osx-64::tzcode-2019a-h01d97ff_1002
  xerces-c           conda-forge/osx-64::xerces-c-3.2.2-h8f8adb3_1004
  zstd               conda-forge/osx-64::zstd-1.4.4-hed8d7c8_2



Downloading and Extracting Packages
libnetcdf-4.7.4      | 1.2 MB    | ##################################################################################### | 100% 
Preparing transaction: done
Executing transaction: done
(GEOTEST) user:~ user $ python -c 'import geopandas'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/user/miniconda3/envs/GEOTEST/lib/python3.7/site-packages/geopandas/__init__.py", line 5, in <module>
    from geopandas.io.file import read_file  # noqa
  File "/Users/user/miniconda3/envs/GEOTEST/lib/python3.7/site-packages/geopandas/io/file.py", line 6, in <module>
    import fiona
  File "/Users/user/miniconda3/envs/GEOTEST/lib/python3.7/site-packages/fiona/__init__.py", line 84, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/Users/user/miniconda3/envs/GEOTEST/lib/python3.7/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/Users/user/miniconda3/envs/GEOTEST/lib/python3.7/site-packages/fiona/ogrext.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libnetcdf.15.dylib
  Referenced from: /Users/user/miniconda3/envs/GEOTEST/lib/libgdal.26.dylib
  Reason: image not found
```

**Comment by jGaboardi** [comment]
Being addressed upstream. See conda-forge/fiona-feedstock#159

**Comment by jGaboardi** [comment]
This appears to be resolved. [Tests needing `geopandas`](https://github.com/pysal/spaghetti/runs/546589981#step:6:28) are being skipped in `spaghetti`.

**Comment by jGaboardi** [comment]
[voronoi tests](https://github.com/pysal/libpysal/runs/546676342#step:7:220) that were failing (or being skipped) previously are now passing.
